export const timeLineElements = [
  {
    id: 1,
    title: 'MERN social media app',
    subtitle: 'React, Node, Express, MongoDB',
    description:
      'Social media app with post, like, comment  and notification functionality. Front-end and back-end. Fully functioning application. Not live product, just for portfolio.',
    buttonText: 'Go to projects',
    date: 'November 2021',
    icon: 'app',
  },
  {
    id: 2,
    title: 'Node, Express, MongoDB',
    subtitle: 'Udemy course',
    description: 'Started learning back-end development.',
    date: 'October 2021',
    icon: 'study',
  },
  {
    id: 3,
    title: 'Production Feedback app',
    subtitle: 'React, Firebase Database, Live Notifications, auth',
    description:
      'Live feedback from production workers to master worker. Web application built with React as front-end and Firebase as back-end.',
    buttonText: 'Go to projects',
    date: 'October 2021',
    icon: 'app',
  },
  {
    id: 4,
    title: 'React JS',
    subtitle: 'Udemy course',
    description: 'Started learning JavaScript framework React JS',
    date: 'February 2021',
    icon: 'study',
  },
  {
    id: 5,
    title: 'Real-estate website',
    subtitle: 'HTML, CSS, JavaScript',
    description:
      'Fully functioning real-estate website. Custom floor plan explorer.',
    buttonText: 'Go to projects',
    date: 'September 2020',
    icon: 'app',
  },
  {
    id: 6,
    title: 'HTML, CSS, JavaScript',
    subtitle: 'Udemy course',
    description: 'Started learning web application development.',
    date: 'April 2020',
    icon: 'study',
  },
  {
    id: 7,
    title: 'Warehouse management app',
    subtitle: 'Java, Android, MVVM, Room Database, LiveData',
    description:
      'Android app for special warehouse management. For receiving products and for releasing goods for production.',
    buttonText: 'Go to projects',
    date: 'January 2020',
    icon: 'app',
  },
  {
    id: 8,
    title: 'Started learning Android Development with Java',
    subtitle: 'Udemy course',
    description: 'My first "Hello world" app.',
    date: 'July 2019',
    icon: 'study',
  },
];

export const projects = [
  {
    id: 1,
    title: 'Portfolio website',
    mainTech: 'React',
    tech: [
      'React JS',
      'Html',
      'Css',
      'Styled-components',
      'React-scroll',
      'react-vertical-timeline-component',
      'react-icons',
      'aos',
    ],
    shortDesc: 'Portfolio website',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/portfolio_dark.jpeg',
    mainBtn: 'Website',
    website: '',
    github: 'https://github.com/Krixxx/portfolio',
  },
  {
    id: 2,
    title: 'Social media website',
    mainTech: 'React',
    tech: [
      'React JS',
      'Html',
      'Css',
      'Styled-components',
      'Axios',
      'Material-ui',
      'Authorization',
      'useReducer',
      'useContext',
      'react-router-dom',
    ],
    shortDesc:
      'Fully functioning MERN social media website front-end. Create and delete posts, like and unlike posts, add comments to posts, edit user data. Made for learning purposes and for portfolio.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/social_main.jpeg',
    mainBtn: 'Website',
    website: '',
    github: 'https://github.com/Krixxx/social-media-client',
  },
  {
    id: 3,
    title: 'Social media website API',
    mainTech: 'Node',
    tech: [
      'Node JS',
      'Express',
      'Mongoose',
      'Mongodb',
      'Jsonwebtoken',
      'Auth',
      'Middleware',
    ],
    shortDesc:
      'Fully functioning MERN social media application back-end. Authentication, CRUD, JWT, image upload, server side pagination. For learning and for portfolio.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/social_main.jpeg',
    mainBtn: 'Website',
    website: '',
    github: 'https://github.com/Krixxx/social-media-api',
  },
  {
    id: 4,
    title: 'Notification and alert app',
    mainTech: 'React',
    tech: [
      'React JS',
      'Html',
      'Css',
      'Firebase',
      'Realtime database',
      'Styled-components',
      'Auth',
      'Context',
      'react-router-dom',
    ],
    shortDesc:
      'Application for manufacturing company. Workers can ask work and send alerts in real-time to department manager dashboard. Built in React, for back-end I used Firebase realtime database. Real-life application.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/production.jpeg',
    mainBtn: 'Demo',
    website: 'https://production-notification-krix.netlify.app',
    github: 'https://github.com/Krixxx/omblus',
  },
  {
    id: 5,
    title: 'E-Commerce Project',
    mainTech: 'React',
    tech: [
      'React JS',
      'Html',
      'Css',
      'Axios',
      'Stripe payment',
      'Styled-components',
      'auth0',
      'useReducer',
      'useContext',
      'react-router-dom',
    ],
    shortDesc:
      'Udemy course learning project. Basic functionality of e-commerce website. Filtering products with multiple options, checkout page, making payment with stripe, authorization with auth0.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/store_sample.jpeg',
    mainBtn: 'Demo',
    website: 'https://store-sample-krix.netlify.app/',
    github: 'https://github.com/Krixxx/store-sample',
  },
  {
    id: 6,
    title: 'Search Github Users',
    mainTech: 'React',
    tech: [
      'React JS',
      'Html',
      'Css',
      'Styled-components',
      'auth0',
      'Axios',
      'React Icons',
      'Fusioncharts',
      'Context',
      'react-router-dom',
    ],
    shortDesc:
      'Udemy course learning project. Fetch data from API, use react-router-dom for pages, Fusioncharts for charting and auth0 for authentication.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/github_users.jpeg',
    mainBtn: 'Demo',
    website: 'https://git-user-search-krix.netlify.app/',
    github: 'https://github.com/Krixxx/user-search',
  },
  {
    id: 7,
    title: 'Real-estate website',
    mainTech: 'JS',
    tech: ['Html', 'Css', 'JS'],
    shortDesc:
      'Real-life project for real-estate development project. Custom floorplan solution.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/limonaadivabrik.jpeg',
    mainBtn: 'Demo',
    website: '',
    github: 'https://github.com/Krixxx/omblus',
  },
  {
    id: 8,
    title: 'Company website',
    mainTech: 'JS',
    tech: ['Html', 'Css', 'JS'],
    shortDesc:
      'Learning project - creating responsive website for a small production company',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/kummitehas.jpeg',
    mainBtn: 'Demo',
    website: '',
    github: 'https://github.com/Krixxx/omblus',
  },
  {
    id: 9,
    title: 'Warehouse app',
    mainTech: 'Java',
    tech: [
      'Java',
      'Android',
      'LiveData',
      'Room Database',
      'MVVM architecture',
      'File import',
    ],
    shortDesc:
      'Real-life project. Warehouse workers get purchase order file as input and then can start registering arrived products. In case of a problem, user can make a note in the app and eventually send raport to purchaser. Second part of app is for releasing products according to product plan. Worker get product plan to the app and then they can start marking itmes, that they have given out.',
    longDesc: '',
    imageUrl: 'http://localhost:3000/assets/img/portfolio/mat_ladu_1.jpeg',
    mainBtn: 'Demo',
    website: '',
    github: 'https://github.com/Krixxx/Porolooniladu',
  },
];
